package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseActualData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActualData extends BaseActualData<ActualData> {
	public static final ActualData dao = new ActualData();
}
