package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company();
}
