package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseWaterMeter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaterMeter extends BaseWaterMeter<WaterMeter> {
	public static final WaterMeter dao = new WaterMeter();
}
