package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseWaterIndex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaterIndex extends BaseWaterIndex<WaterIndex> {
	public static final WaterIndex dao = new WaterIndex();
}
