package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseWell;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Well extends BaseWell<Well> {
	public static final Well dao = new Well();
}
